### ISSUE TITLE
Opie_Elvui LUA errors

### ISSUE THREAD

**Issue by Trenchfoote** [AcidWeb/OPie_ElvUI#1]
Running the current release, upon logging in, getting a suite of errors. See attached. No performance issues, addon works, just bugsack catching a bunch.
![World Of Warcraft Screenshot 2023 03 23 - 10 58 57 05](https://user-images.githubusercontent.com/128204689/227245278-3a7bfd21-4f90-436d-bfa3-eb095a508cec.png)
![World Of Warcraft Screenshot 2023 03 23 - 10 59 07 62](https://user-images.githubusercontent.com/128204689/227245302-3497c9b8-6a80-4132-b482-dd61c0181b8e.png)

**Comment by AcidWeb** [comment]
Please verify your installation as it looks like `Libs` directory is missing.

**Comment by Trenchfoote** [comment]
Pulling install from here through the Git app and symlink to my addons folder.

**Comment by AcidWeb** [comment]
That will not work as bare repository don't contain all files.

**Comment by Trenchfoote** [comment]
Alrighty, pulling from wago. Thanks for the reply!
